<?php
/*
Plugin Name: Bulk Email Client
Description: Simple admin interface to send bulk emails using KT_AIBulkMailer_ES
Version: 0.1.0
Author: AutoGenerated
*/

if (!defined('ABSPATH')) exit;

class KT_BulkEmail_Client {
    const NONCE = 'kt_abm_nonce';

    public function __construct(){
        add_action('admin_menu', [$this,'menu']);
        add_action('admin_enqueue_scripts', [$this,'enqueue']);
    }

    public function menu(){
        add_menu_page(
            __('Bulk Email Client','kt-abmc'),
            __('Bulk Email Client','kt-abmc'),
            'manage_options',
            'kt-bulkemail-client',
            [$this,'page'],
            'dashicons-email',
            59
        );
    }

    public function enqueue($hook){
        if($hook !== 'toplevel_page_kt-bulkemail-client') return;
        wp_enqueue_script(
            'kt-bulkemail-client',
            plugin_dir_url(__FILE__).'bulkemail-client.js',
            ['jquery'],
            '0.1.0',
            true
        );
        wp_localize_script('kt-bulkemail-client','KT_BEC',[
            'ajax'=>admin_url('admin-ajax.php'),
            'nonce'=>wp_create_nonce(self::NONCE)
        ]);
    }

    public function page(){
        echo '<div class="wrap">';
        echo '<h1>'.esc_html__('Bulk Email Client','kt-abmc').'</h1>';
        echo '<p>'.esc_html__('Enter comma-separated emails, subject and body to send bulk messages using the bulkemail server plugin.','kt-abmc').'</p>';
        echo '<textarea id="bec-emails" style="width:100%;height:80px" placeholder="correo1@example.com, correo2@example.com"></textarea>';
        echo '<input id="bec-subject" type="text" style="width:100%;margin-top:10px" placeholder="'.esc_attr__('Subject','kt-abmc').'" />';
        echo '<textarea id="bec-body" style="width:100%;height:160px;margin-top:10px" placeholder="'.esc_attr__('Body','kt-abmc').'"></textarea>';
        echo '<button id="bec-send" class="button button-primary" style="margin-top:10px">'.esc_html__('Send','kt-abmc').'</button>';
        echo '<pre id="bec-output" style="margin-top:10px;white-space:pre-wrap"></pre>';
        echo '</div>';
    }
}

new KT_BulkEmail_Client();
?>
